"""Regenerate ``docs/providers.md``'s capability matrix from the adapters' own declarations.

Development plan Phase 4, acceptance criterion 2: "The capability matrix in ``docs/providers.md``
is generated from the adapters' declarations, not hand-written." Every row below comes from calling
each adapter's real :meth:`~modelrack.provider.Provider.capabilities` — never a transcription a
future capability change could leave stale — which is exactly the failure mode a hand-maintained
table invites and this script exists to rule out. Constructing an adapter here makes no network
call: :meth:`capabilities` is cheap and non-probing by contract (spec §7), so no base URL needs to
be reachable for this script to run.

Run after adding a provider or changing a capability declaration::

    python scripts/generate_providers_doc.py

The output is committed. This script does not run in CI, matching BaseAiCore's
``scripts/generate_api_reference.py`` — a stale ``docs/providers.md`` is caught by review, not by
a build failure, until this package has a doc-drift job.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from modelrack.provider import ProviderCapabilities
from modelrack.providers.ollama import OllamaProvider
from modelrack.providers.openai_compatible import OpenAICompatibleProvider
from modelrack.testing import FakeProvider

if TYPE_CHECKING:
    from modelrack.provider import Provider

_OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "providers.md"

_FLAG_LABELS: tuple[tuple[str, str], ...] = (
    ("streaming", "Streaming"),
    ("tool_calling", "Tool calling"),
    ("structured_output", "Structured output (JSON Schema)"),
    ("json_mode", "JSON mode"),
    ("token_counts", "Token counts"),
    ("token_level_chunks", "One delta = one token"),
    ("thinking_control", "Thinking control"),
    ("logprobs", "Log probabilities"),
    ("force_unload", "Explicit load/unload"),
    ("residency_query", "Residency query"),
    ("kv_metrics", "KV-cache metrics"),
    ("context_configurable", "Caller-chosen context"),
    ("embedding", "Embeddings"),
)

_PROVIDERS: tuple[tuple[str, str, Provider], ...] = (
    ("FakeProvider", "`modelrack.testing.FakeProvider`", FakeProvider()),
    (
        "OllamaProvider",
        "`modelrack.providers.ollama.OllamaProvider`",
        OllamaProvider(base_url="http://127.0.0.1:11434"),
    ),
    (
        "OpenAICompatibleProvider",
        "`modelrack.providers.openai_compatible.OpenAICompatibleProvider`",
        OpenAICompatibleProvider(base_url="http://127.0.0.1:8080"),
    ),
)


def _mark(value: bool) -> str:
    """Render one capability flag as a table cell."""
    return "✅" if value else "—"


def _render_table(rows: tuple[tuple[str, str, ProviderCapabilities], ...]) -> str:
    """Render the capability matrix as a GitHub-flavoured Markdown table."""
    header = "| Capability | " + " | ".join(name for name, _, _ in rows) + " |"
    divider = "|---|" + "---|" * len(rows)
    lines = [header, divider]
    for flag, label in _FLAG_LABELS:
        cells = [_mark(bool(getattr(capabilities, flag))) for _, _, capabilities in rows]
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def render() -> str:
    """Build the full contents of ``docs/providers.md``."""
    rows = tuple((name, path, provider.capabilities()) for name, path, provider in _PROVIDERS)
    table = _render_table(rows)
    adapter_list = "\n".join(f"* {path}" for _, path, _ in _PROVIDERS if path.count("Fake") == 0)
    return f"""# ModelRack — Provider capability matrix

Generated by `scripts/generate_providers_doc.py` from each adapter's own
`Provider.capabilities()` — never hand-edited (development plan Phase 4, acceptance criterion 2).
Regenerate after adding a provider or changing a declaration.

Every flag here is a promise, not a guess ([spec §11.10](packages/modelrack/spec.md) and
[ADR-0007](adr/0007-provider-abstraction.md) rule 2): a caller checks
`capabilities()` and branches, and an adapter that declares `False` refuses the corresponding
request with `CapabilityUnsupported` rather than silently degrading it.

{table}

## Real adapters

{adapter_list}

`FakeProvider` is included because it is the suite's third shipped implementation of `Provider`,
reached through `modelrack.testing` (spec §7), and its *default* script declares every
capability — `modelrack.testing.MINIMAL_CAPABILITIES` is available for a test that needs the
weakest provider a consumer must survive instead.
"""


def main() -> None:
    """Regenerate ``docs/providers.md`` in place."""
    _OUTPUT.write_text(render())


if __name__ == "__main__":
    main()
